// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDia3GUtqlY1pYZoACtjCU_a6p1mZCIS4U',
    appId: '1:251979334495:web:b7c3ff45cdd128f9392cea',
    messagingSenderId: '251979334495',
    projectId: 'weather-98e0b',
    authDomain: 'weather-98e0b.firebaseapp.com',
    storageBucket: 'weather-98e0b.appspot.com',
    measurementId: 'G-WMSYHWZXFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsDSzigzXfr1cbDOCMifUGas6zYUy-Jsw',
    appId: '1:251979334495:android:3c5492f065c96807392cea',
    messagingSenderId: '251979334495',
    projectId: 'weather-98e0b',
    storageBucket: 'weather-98e0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPd-xtEQGNJG5BPbh80_dnbZ5Z_1O-ZHw',
    appId: '1:251979334495:ios:c51ccf8ec8688633392cea',
    messagingSenderId: '251979334495',
    projectId: 'weather-98e0b',
    storageBucket: 'weather-98e0b.appspot.com',
    iosBundleId: 'com.weather.app.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPd-xtEQGNJG5BPbh80_dnbZ5Z_1O-ZHw',
    appId: '1:251979334495:ios:7842f94c69c3bc89392cea',
    messagingSenderId: '251979334495',
    projectId: 'weather-98e0b',
    storageBucket: 'weather-98e0b.appspot.com',
    iosBundleId: 'com.weather.app.weatherApp.RunnerTests',
  );
}
